### PR TITLE
Fix duplicate fields bugs

### LINKED ISSUE #163: Fix duplicate phone numbers
Everyone contact should have a unique phone number, duplicate phone numbers should not be allowed

### LINKED ISSUE #165: Fix phone number requirements
Phone numbers with 3-6 digits should not be allowed

### LINKED ISSUE #166: Fix duplicate email handling
Duplicate emails should not be allowed

### LINKED ISSUE #167: Fix duplicate telegram handle bug
There should be no duplicate telegram handles in the address book

### LINKED ISSUE #181: Fix duplicate name bug
Allow duplicate names as long as contact details (phone number, telegram handle or email) are different

### PR DESCRIPTION
**Pull request by zienxu**
Prevents duplicate phone numbers, emails or telegram handles but allow duplicate names as long as none of these fields are identical as two people can have the same name in real life.
closes #163 
closes #165 
closes #166 
closes #167 
closes #181

### CODE REVIEW

File: src/test/java/seedu/address/model/AddressBookTest.java [hunk 1]
```diff
@@ -102,6 +105,24 @@ private static class AddressBookStub implements ReadOnlyAddressBook {
         public ObservableList<Person> getPersonList() {
             return persons;
         }
+
+        @Override
+        public boolean hasTelegramHandle(TelegramHandle telegramHandle) {
+            // This is a stub method for testing purposes, returning fa
```
Comment (SlothyCat) [inline src/test/java/seedu/address/model/AddressBookTest.java]: The comment seems to be incomplete. Did you mean returning true? 🤔

File: src/test/java/seedu/address/model/AddressBookTest.java [hunk 2]
```diff
@@ -102,6 +105,24 @@ private static class AddressBookStub implements ReadOnlyAddressBook {
...
+
+        @Override
+        public boolean hasPhoneNumber(Phone phone) {
+            // This is a stub method for testing purposes, returning false by default.
+            return true;
+        }
+
+        @Override
+        public boolean hasEmail(Email email) {
+            // This is a stub method for testing purposes, returning fa
```
Comment (SlothyCat) [inline src/test/java/seedu/address/model/AddressBookTest.java]: This comment seems to have a similar issue to the previous one

File: src/test/java/seedu/address/model/person/PersonTest.java [hunk 3]
```diff
@@ -35,7 +35,7 @@ public void isSamePerson() {
         // same name, all other attributes different -> returns true
```
Comment (SlothyCat) [inline src/test/java/seedu/address/model/person/PersonTest.java]: May consider changing this comment to return false, so that it is consistent with the code

**Review by SlothyCat — CHANGES_REQUESTED** [review]
Looks good generally, other than some small issues with comments

File: src/main/java/seedu/address/model/person/Person.java [hunk 4]
```diff
@@ -97,7 +97,15 @@ public boolean isSamePerson(Person otherPerson) {
         }
 
         return otherPerson != null
-                && otherPerson.getName().equals(getName());
+                // && otherPerson.getName().equals(getName());
```
Comment (achl1012) [inline src/main/java/seedu/address/model/person/Person.java]: Would it be better to remove this comment, if the line of code is no longer being used?

**Review by achl1012 — CHANGES_REQUESTED** [review]
everything looks good, just a minor issue with code comments

**Review by SlothyCat — DISMISSED** [review]
LGTM!

**Review by achl1012 — APPROVED** [review]
lgtm! 😄
